mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy


app_name = 'common'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    # 비밀번호 초기화 요청 폼
    path('password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='common/password_reset_form.html',
            email_template_name='registration/password_reset_email.html',
            success_url=reverse_lazy('common:password_reset_done')
        ), name='password_reset'),

    # 비밀번호 이메일 전송 완료 안내
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='common/password_reset_done.html'),
        name='password_reset_done'),

    # 이메일 링크 클릭 후 비밀번호 재설정 폼(uidb64, token 포함)
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='common/password_reset_confirm.html',
            success_url=reverse_lazy('common:password_reset_complete')
        ), name='password_reset_confirm'),

    # 비밀번호 재설정 완료 안내
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name='common/password_reset_complete.html'),
        name='password_reset_complete'),
    
    # 로그인한 사용자가 비밀번호 변경
    path('password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='common/password_change_form.html',
            success_url=reverse_lazy('common:password_change_done')
        ), name='password_change'),

    path('password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(template_name='common/password_change_done.html'),
        name='password_change_done'),

    # 프로필 관련
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

from pybo import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
    path('accounts/', include('allauth.urls')),
]

handler404 = 'common.views.page_not_found'

mysite/pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views


app_name = 'pybo'


urlpatterns = [
    # base_views.py
    path('',
        base_views.index, name='index'),
    path('<int:question_id>/',
        base_views.detail, name='detail'),
    path('category/<int:category_id>/',
        base_views.index, name='index_by_category'),

    # question_views.py
    path('question/create/',
        question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
        question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
        question_views.question_delete, name='question_delete'),
    
    # answer_views.py
    path('answer/create/<int:question_id>/',
        answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
        answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', 
        answer_views.answer_delete, name='answer_delete'),
    
    # comment_views.py
    path('comment/create/question/<int:question_id>/', 
        comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
        comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
        comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', 
        comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', 
        comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', 
        comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/',
        vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/',
        vote_views.vote_answer, name='vote_answer'),
]

mysite/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count
import logging


from ..models import Question, Answer, Category, QuestionView


logger = logging.getLogger('pybo')


def index(request, category_id=None):
    # pybo 목록 출력
    
    logger.info("INFO 레벨로 출력")
    # 입력 인자
    page = request.GET.get('page', '1') # 페이지
    kw = request.GET.get('kw', '') # 검색어
    so = request.GET.get('so', 'recent') # 정렬 기준

    # 전체 카테고리 목록 조회
    categories = Category.objects.all()

    # 선택된 카테고리 객체 가져오기(없다면 None)
    if category_id:
        category = get_object_or_404(Category, pk=category_id)
    else:
        category = None

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(
            num_answer=Count('answer')).order_by('-num_answer', '-views', '-create_date')
    else: # recent
        question_list = Question.objects.order_by('-create_date')

    # 카테고리별 필터링(category_id 있으면 해당 카테고리만)
    if category:
        question_list = question_list.filter(category=category)

    # 조회
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) | # 제목 검색
            Q(content__icontains=kw) | # 내용 검색
            Q(author__username__icontains=kw) | # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw) # 답변 글쓴이 검색
        ).distinct()

    # 페이징 처리
    paginator = Paginator(question_list, 10) # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list':page_obj,'categories':categories, 'category':category, 'page': page, 'kw':kw, 'so': so}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    # pybo 내용 출력

    # 입력 인자
    page = request.GET.get('page', '1')
    so = request.GET.get('so', 'recent')

    # 조회
    question = get_object_or_404(Question, pk=question_id)
    ip = get_client_ip(request)

    # 이미 조회한 적이 있는지 확인하기
    if not QuestionView.objects.filter(question=question, ip_address=ip).exists():
        # 처음 조회하는 경우에만 죄후 증가
        question.views += 1
        question.save(update_fields = ['views'])

        # 조회 기록 저장
        QuestionView.objects.create(question=question, ip_address=ip)

    # 정렬
    if so == 'recommend':
        answer_list = Answer.objects.filter(question=question).annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        answer_list = Answer.objects.filter(question=question).annotate(
            num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    else: # recent
        answer_list = Answer.objects.filter(question=question).order_by('-create_date')
        
    # 페이징 처리
    paginator = Paginator(answer_list, 5)
    page_obj = paginator.get_page(page)

    context = {'question': question, 'answer_list':page_obj, 'so':so}
    return render(request, 'pybo/question_detail.html', context)

def get_client_ip(request):
    # 클라이언트 IP주소를 가져오는 함수
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.7.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

mysite/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
        <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

mysite/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>    
    </button>

    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <!-- 카테고리 메뉴 -->
        <ul class="navbar-nav mr-auto">
            {% for cat in categories %}
            <li class="nav-item">
                <a class="nav-link{% if category and category.id == cat.id %} active {% endif %}" href="{% url 'pybo:index_by_category' cat.id %}">{{ cat.name }}</a>
            </li>
            {% endfor %}
        </ul>

        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <!-- 프로필 드롭다운 메뉴 추가 -->
                <div class="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-expanded="false">{{ user.username }}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'common:profile' %}">내 프로필</a>
                        <a class="dropdown-item" href="{% url 'common:edit_profile' %}">프로필 편집</a>
                        <a class="dropdown-item" href="{% url 'common:password_change' %}">비밀번호 변경</a>
                        <div class="dropdown-divider"></div>
                        <form action="{% url 'common:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="dropdown-item">로그아웃</button>
                        </form>
                    </div> 
                </div>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>