mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy


app_name = 'common'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    # 비밀번호 초기화 요청 폼
    path('password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='common/password_reset_form.html',
            email_template_name='registration/password_reset_email.html',
            success_url=reverse_lazy('common:password_reset_done')
        ), name='password_reset'),

    # 비밀번호 이메일 전송 완료 안내
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='common/password_reset_done.html'),
        name='password_reset_done'),

    # 이메일 링크 클릭 후 비밀번호 재설정 폼(uidb64, token 포함)
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='common/password_reset_confirm.html',
            success_url=reverse_lazy('common:password_reset_complete')
        ), name='password_reset_confirm'),

    # 비밀번호 재설정 완료 안내
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name='common/password_reset_complete.html'),
        name='password_reset_complete'),
    
    # 로그인한 사용자가 비밀번호 변경
    path('password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='common/password_change_form.html',
            success_url=reverse_lazy('common:password_change_done')
        ), name='password_change'),

    path('password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(template_name='common/password_change_done.html'),
        name='password_change_done'),

    # 프로필 관련
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

from pybo import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
    path('accounts/', include('allauth.urls')),
]

handler404 = 'common.views.page_not_found'

mysite/pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views


app_name = 'pybo'


urlpatterns = [
    # base_views.py
    path('',
        base_views.index, name='index'),
    path('<int:question_id>/',
        base_views.detail, name='detail'),
    path('category/<int:category_id>/',
        base_views.index, name='index_by_category'),

    # question_views.py
    path('question/create/',
        question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
        question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
        question_views.question_delete, name='question_delete'),
    
    # answer_views.py
    path('answer/create/<int:question_id>/',
        answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
        answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', 
        answer_views.answer_delete, name='answer_delete'),
    
    # comment_views.py
    path('comment/create/question/<int:question_id>/', 
        comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
        comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
        comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', 
        comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', 
        comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', 
        comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/',
        vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/',
        vote_views.vote_answer, name='vote_answer'),
]

mysite/common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)

    def __str__(self):
        return f'{self.user.username}의 프로필'
    
# 시그널을 사용해서 User가 생성될 때, 자동으로 Profile 발생
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

mysite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


from .models import Profile


class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')

    class Meta:
        model = User
        fields = ("username", "email")

# 프로필 편집을 위한 새로운 폼
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'birth_date', 'profile_image']
        widgets = {
            'birth_date' : forms.DateInput(attrs={'type':'date'}),
            'bio' : forms.Textarea(attrs={'rows':4, 'cols':50}),
        }

# User 정보 수정을 위한 폼 (비밀번호 필드 제외)
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

mysite/common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from common.forms import UserForm, ProfileForm, UserUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages



def signup(request):
    # 회원가입
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

@login_required(login_url='common:login')
def profile(request):
    # 프로필 확인
    context = {'user': request.user }
    return render(request, 'common/profile.html', context)

@login_required(login_url='common:login')
def edit_profile(request):
    # 프로필 편집
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, '프로필이 설공적으로 업데이트 되었습니다.')
            return redirect('common:profile')
    
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    context = {
        'user_form' : user_form,
        'profile_form' : profile_form
    }

    return render(request, 'common/edit_profile.html', context)

def page_not_found(request, exception):
    # 404 page not found
    return render(request, 'common/404.html', {})

mysite/templates/common/edit_profile.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-3">
    <div class="row my-3">
        <div class="col-12">
            <h3>프로필 편집</h3>
        </div>
    </div>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true">%time;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>사용자 정보</label>
            {{ user_form.as_p }}
        </div>

        <div class="form-group">
            <label>프로필 정보</label>
            {{ profile_form.as_p }}
        </div>

        <button type="submit" class="btn btn-primary">저장</button>
        <a href="{% url 'common:password_change' %}" class="btn btn-secondary">비밀번호 변경</a>
        <a href="{% url 'common:profile' %}" class="btn btn-secondary">취소</a>
    </form>
</div>
{% endblock %}

mysite/templates/common/login.html
{% extends 'base.html' %}
{% load socialaccount %}

{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-6">
            <h4>로그인</h4>
            <div class="text-right mb-3">
                <span>
                    또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a>
                </span>
            </div>

            <form method="post" class="post-form" action="{% url 'common:login' %}">
                {% csrf_token %}
                <!-- 로그인 성공 후 이동되는 URL -->
                <input type="hidden" name="next" value="{{ next }}">
                {% include 'form_errors.html' %}
                <div class="form-group">
                    <label for="username">사용자ID</label>
                    <input type="text" class="form-control" name="username" id="username"
                    value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="password">비밀번호</label>
                    <input type="password" class="form-control" name="password" id="password"
                    value="{{ form.password.value|default_if_none:'' }}">
                </div>
                <button type="submit" class="btn btn-primary">로그인</button>
                <div class="text-left mt-3">
                    <small><a href="{% url 'common:password_reset' %}">비밀번호를 잊어셨나요?</a></small>
                </div>
            </form>
        </div>

        <div class="col-6">
            <!-- 소셜 로그인 버튼 -->
            <h5>소셜 로그인</h5>
            <div class="d-grid gap-2">
                <a href="{% provider_login_url 'google' %}" class="btn btn-danger btn-block">
                    Google로 로그인
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mysite/templates/common/password_change_done.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-12">
            <h4>비밀번호 변경 완료</h4>
        </div>
    </div>
    <div class="alert alert-success">
        <strong>변경 완료!</strong>
        비밀번호가 성공적으로 변경되었습니다.
    </div>
    <a href="{% url 'pybo:index' %}" class="btn btn-primary">메인 페이지로 돌아가기</a>
</div>
{% endblock %}

mysite/templates/common/password_change_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>비밀번호 변경</h4>
        </div>
        <div class="col-8 text-right">
            <span>
                <a href="{% url 'pybo:index' %}">메인 페이지로</a>
            </span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="old_password">현재 비밀번호</label>
            <input type="password" class="form-control" name="old_password" id="old_password">
        </div>
        <div class="form-group">
            <label for="new_password1">새 비밀번호</label>
            <input type="password" class="form-control" name="new_password1" id="new_password1">
        </div>
        <div class="form-group">
            <label for="new_password2">새 비밀번호 확인</label>
            <input type="password" class="form-control" name="new_password2" id="new_password2">
        </div>
        <button type="submit" class="btn btn-primary">비밀번호 변경</button>
    </form>
</div>
{% endblock %}

mysite/templates/common/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-12">
            <h4>비밀번호 변경 완료</h4>
        </div>
    </div>
    <div class="alert alert-success">
        <strong>성공!</strong>
        비밀번호가 성공적으로 변경되었습니다.<br>
        새로운 비밀번호로 로그인 할 수 있습니다.
    </div>
    <a href="{% url 'common:login' %}" class="btn btn-primary">로그인하기</a>
</div>
{% endblock %}

mysite/templates/common/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>새 비밀번호 설정</h4>
        </div>
        <div class="col-8 text-right">
            <span>
                <a href="{% url 'common:login' %}">로그인 페이지로</a>
            </span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="new-password">새 비밀번호</label>
            <input type="password" class="form-control" name="new_password1" id="new_password1">
        </div>
        <div class="form-group">
            <label for="new_password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="new_password2" id="new_password2">
        </div>
        <button type="submit" class="btn btn-primary">비밀번호 변경</button>
    </form>
</div>
{% endblock %}

mysite/templates/common/password_reset_done.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row-">
        <div class="col-12">
            <h4>비밀번호 재설정 이메일 전송 완료</h4>
        </div>
    </div>
    <div class="alert alert-info">
        <strong>이메일을 확인하세요!</strong>
        비밀번호 재설정 링크가 포함된 이메일을 발송했습니다.<br>
        받은 메일함을 확인하고 링크를 클릭하여 비밀번호를 재설정하세요.
    </div>
    <a href="{% url 'common:login' %}" class="btn btn-secondary">로그인 페이지로 돌아가기</a>
</div>
{% endblock %}

mysite/templates/common/password_reset_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>비밀번호 찾기</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="email">이메일 주소</label>
            <input type="email" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">이메일 전송</button>
    </form>
</div>
{% endblock %}

mysite/templates/common/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-md-4">
            {% if user.profile.profile_imege %}
                <img src="{{ user.profile.profile_image.url }}" class="img-fluid rounded-circle" alt="프로필 사진">
            {% else %}
                <div class="bg-secondary rounded-circle d-flex align-items-center justify-content-center" style="width:150px; height:150px;">
                    <i class="fas fa-user fa-3x text-white"></i>
                </div>
            {% endif %}
        </div>
        <div class="col-md-8">
            <h2>{{ user.username }} 님의 프로필</h2>
            <p><strong>이름:</strong> {{ user.first_name }}{{ user.last_name }}</p>
            <p><strong>이메일:</strong> {{ user.email }}</p>
            <p><strong>생년월일:</strong> {{ user.profile.birth_date|default:"설정되지 않음" }}</p>
            <p><strong>소개:</strong> {{ user.profile.bio|default:"소개글이 없습니다." }}</p>

            <a href="{% url 'common:edit_profile' %}" class="btn btn-primary">프로필 편집</a>
            <a href="{% url 'common:password_change' %}" class="btn btn-warning">비밀번호 변경</a>
        </div>
    </div>
</div>
{% endblock %}

mysite/templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>회원가입</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class='post-form'>
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" 
            value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
            value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
            value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}